#!/bin/bash
# /etc/init.d/assistant
 
### BEGIN INIT INFO
# Description: This service is used to start the python script
### END INIT INFO
 
case "$1" in
    start)
        echo "Starting Voice Assistant"
        python /home/pi/VoiceAssistant/VoiceAssistant.py &
        ;;
    stop)
        echo "Stopping Voice Assistant"
        #killall ledblink.py
        kill $(ps aux | grep -m 1 'python /home/pi/VoiceAssistant/VoiceAssistant.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service ledblink start|stop"
        exit 1
        ;;
esac
exit 0
